{% set name = "rubin-nights" %}
{% set version = "0.6.1" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/rubin_nights-{{ version }}.tar.gz
  sha256: dcba696901a8c552c5538db2703d4bedae77273416b10b9418a4d9c420e22d67

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm >=8
    - pip
  run:
    - python >={{ python_min }}
    - astropy-base
    - astroplan
    - healpy
    - httpx
    - lsst-ts-xml
    - matplotlib-base
    - numpy
    - pandas
    - psycopg
    - pyvo
    - pyyaml
    - rubin-scheduler
    - rubin-sim
    - sqlalchemy

test:
  imports:
    - rubin_nights
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}
    - lxml

about:
  home: https://github.com/lsst-sims/rubin_nights
  summary: Tools to access Rubin nightly observing data
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rhiannonlynne
